# -*- coding: utf-8 -*-
"""Laberinto

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vYPd5ruQ3QYnrIVyDEL6NwuE9yYPFTQl
"""

import random
import numpy as np

def crearMatriz(x,y):
  matriz = np.random.randint(0, 2, size=(x, y))
  matriz[0][0] = 0 #entrada
  matriz[-1][-1] = 2 #salida
  return matriz

matriz = crearMatriz(10,10)
print(matriz)